# Generated by Django 5.1.3 on 2025-02-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
